feature1
kmhm212/learning_plan pull request #1
Opened 2021-05-04 01:28 UTC by kmhm212

2021-05-04 03:16 UTC, yukishimizumg reviewed
@kmhm212 
コメントしましたので、確認お願いします🙏

2021-05-04 03:16 UTC, yukishimizumg commented on _head.html
> +    <title>Document</title>
title 変更お願いします✨

2021-05-04 03:16 UTC, yukishimizumg commented on index.php
> +$done_tasks = findTaskByDate(TASK_DATE_NOT_NULL);
細かいですが、学習計画の名称に対し、plan と task が混在してますが、名称は統一するようにしましょう✨

2021-05-04 03:16 UTC, yukishimizumg commented on index.php
> +                    <!-- 完了済のデータを表示 -->
完了済みのデータは、完了日の降順でデータを表示するように修正お願いします✨

2021-05-04 03:16 UTC, yukishimizumg commented on functions.php
> +function insertValidate($title,$date) {
`,`と`$date`の間に半角スペース入れてください✨

2021-05-04 03:16 UTC, yukishimizumg commented on functions.php
> +        $errors = [];
インデント修正お願いします✨

2021-05-04 03:16 UTC, yukishimizumg commented on index.php
> +                            <td <?php if($task['due_date'] < date("Y-m-d")) echo ('style="color: red"')?>>
CSS は直接指定せず、classを付与して`style.css`で指定するようにしてください✨

2021-05-04 03:16 UTC, yukishimizumg commented on index.php
> +
データを追加後、入力した学習内容と期限日が入力欄に残ってしまうので、[課題のgif画像](https://github.com/elites-team/23rd-century-4th/blob/master/doc/06_php/exercise_org/03_learning_plan/01.md#%E4%B8%BB%E3%81%AA%E6%A9%9F%E8%83%BD)を参考にして修正お願いします✨

<img width="794" alt="Document" src="https://user-images.githubusercontent.com/46326671/116956599-9b15bc00-acd0-11eb-8c1b-d94ce0ac85c0.png">

2021-05-04 03:16 UTC, yukishimizumg commented on index.php
> +                    <!-- 未完了のデータを表示 -->
未完了のデータは、期限日の昇順でデータを表示するように修正お願いします✨

2021-05-04 08:19 UTC, kmhm212 commented on index.php
> +
こちらの訂正はしたのですが、
自分のPCだと入力→「追加」→反映されず→「リロード」→ようやく反映
と、追加から反映に間があるようなのですが、これはPHP上の問題なのか、ブラウザなのか、あまりわからずにいます。もしもPHPで解決できるなら、自分でもいろいろ調べてみます。

2021-05-04 08:19 UTC, kmhm212 commented on functions.php
> +            ORDER BY
こちらの部分に関して。
`NULL`と`NOT NULL` 、 `ASC`と`DESC` を `:date``:order` のように外で定義づけて分岐させたいものの、うまくできずにいます。`bindParam`の使用を理解していないのか`PDO::PARAM_NULL`などでもうまく行かず、このように不格好になってしまっています。参考になるサイトなどありましたら教えて下さいー！

2021-05-04 10:47 UTC, yukishimizumg reviewed
@kmhm212 
コメントしましたので、確認お願いします🙏
[こちら](https://github.com/kmhm212/learning_plan/pull/1#discussion_r625592432)の回答は後程追ってご連絡します！

2021-05-04 10:47 UTC, yukishimizumg commented on functions.php
> +        echo 'class="expired"';
関数は汎用性が高い方が良いので、ここでechoはせずただreturnさせて、呼び元で結果をecho した方が良いです✨
(この関数に関しては多様しないと思いますが覚えておくと良いと思います)

2021-05-04 10:47 UTC, yukishimizumg commented on index.php
> +
ブラウザの問題ではなく、PHPで解決できます👍
手動でリロードしなくて済むためには、登録処理後自動でその作業が実行されるようにしてください。
(学習管理アプリ内の何れかのファイルにヒントがあります)

2021-05-04 10:47 UTC, yukishimizumg commented on index.php
> +
$errors も初期化しましょう✨

2021-05-04 10:47 UTC, yukishimizumg commented on edit.php
> +
$errors も初期化しましょう！

2021-05-04 10:47 UTC, yukishimizumg commented on functions.php
> +function dateColor($plan) {
関数名は「動詞 + 目的語」の命名を推奨します👍

2021-05-04 10:47 UTC, yukishimizumg commented on functions.php
> +            ORDER BY
こちらは後程追ってご連絡します!

2021-05-04 12:07 UTC, kazu-taka requested changes
@kmhm212 
SQLのところでコメントしたので確認お願いします:bow:

2021-05-04 12:07 UTC, kazu-taka commented on config.php
> +define('PLAN_DATE_NOT_NULL', 'NOT NULL');
@kmhm212 
今回であれば、`completion_date`がnullかnull以外のデータをそれぞれ抽出したいということだと思うので、`define('PLAN_COMPLETION_DATE_NULL', true);`にして、index.phpで、NULLを抽出したい時だけ`findPlanByDate(PLAN_COMPLETION_DATE_NULL)`を渡してあげるのがいいと思います✨
`findPlanByDate`関数で($completion_date_null = false)とすることで、引数に何も渡されてこない時は、デフォルト値として、`false`を設定する事が可能になります！ですので、`$done_plans = findPlanByDate();`のように、引数を渡さなくてもエラーにはならなくなります！
`findPlanByDate`で、条件やソート順を切り替える時は、シンプルにif、elseのそれぞれにコードを書いた方が、他の人が見た時も分かりやすいと思います👍


```php
// index.php

$notyet_plans = findPlanByDate(PLAN_COMPLETION_DATE_NULL);
$done_plans = findPlanByDate();


// functions.php
function findPlanByDate($completion_date_null = false)
{
    $dbh = connectDb();
    $sql = <<<EOM
    SELECT
        *
    FROM
        plans
    EOM;
    if (completion_date_null) {
        // ここに処理を書く
    } else {
        // ここに処理を書く
    }

    $stmt = $dbh->prepare($sql);
    $stmt->execute();
    return $stmt->fetchAll(PDO::FETCH_ASSOC);
}
```

ちなみにPDOのbindParamを使って、order byを指定することはできません^^;
https://teratail.com/questions/5848

2021-05-06 21:56 UTC, kazu-taka commented
@kmhm212 
課題1お疲れさまでした！！
![LGTM](https://image.lgtmoon.dev/33970)

2021-05-06 21:59 UTC, merged